CREATE TABLE INV_BATCHS
(
  BATCH_ID             NUMBER(8) primary key,
  BATCH_PRE_FIX        VARCHAR2(8 BYTE),
  BATCH_POST_FIX       NUMBER(8),
  BATCH_NO             VARCHAR2(50 BYTE),
  ITEM_ID              NUMBER(16),
  EXPIRY_DATE          DATE,
  COMPANY_ID           NUMBER(8),
  BRANCH_ID            VARCHAR2(8 BYTE),
  CREATED_BY           NUMBER(8),
  CREATION_DATE        DATE,
  LAST_UPDATED_BY      NUMBER(8),
  LAST_UPDATE_DATE     DATE,
  APPROVED_BY          NUMBER(8),
  APPROVAL_DATE        DATE,
  BATCH_STATUS         VARCHAR2(30 BYTE),
  REMARKS              VARCHAR2(200 BYTE),
  BATCH_QTY            NUMBER(16,4),
  BOM_ID               NUMBER(8),
  BALANCE_QTY          NUMBER(16,4),
  PRODUCED_QTY         NUMBER(16,4),
  WASTE_QTY            NUMBER(16,4),
  WASTE_COST           NUMBER(16,4),
  WASTE_GL_VOUCHER_ID  NUMBER(16),
  BATCH_YIELD          NUMBER(16,4),
  CLOSED_BY            NUMBER(8),
  CLOSED_DATE          DATE,
  BATCH_DATE           DATE
);
