select DISTINCT LPAD(BRANCH_ID,2,'0') FROM sys_user_branches;

SELECT BRANCH_ID FROM sys_user_branches WHERE LENGTH(BRANCH_ID) = 1;

UPDATE SYS_USER_BRANCHES
SET BRANCH_ID = LPAD(BRANCH_ID,2,'0')
WHERE LENGTH(BRANCH_ID) = 1;