truncate table INV_ITEM_CODE_SEGMENT_VALUES;

truncate table INV_ITEMS;

DROP SEQUENCE INV_ITEM_CODE_SEGMENT_VALUES_V;

CREATE SEQUENCE INV_ITEM_CODE_SEGMENT_VALUES_V
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_ITEMS_S;

CREATE SEQUENCE INV_ITEMS_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

insert into GDN.INV_ITEM_CODE_SEGMENT_VALUES gd
(gd.VAL_ID,gd.SEGMENT_ID,gd.SEGMENT_VAL,gd.SEGMENT_VAL_DESC,gd.PARENT_VAL,gd.CREATED_BY,gd.CREATION_DATE,gd.LAST_UPDATED_BY,gd.LAST_UPDATE_DATE)
select n.VAL_ID,n.SEGMENT_ID,n.SEGMENT_VAL,n.SEGMENT_VAL_DESC,n.PARENT_VAL,1,sysdate,1,sysdate 
from nbl.INV_ITEM_CODE_SEGMENT_VALUES n;

insert into gdn.inv_items gi
(gi.ITEM_ID,gi.SEGMENT1,gi.SEGMENT2,gi.SEGMENT3,gi.SEGMENT4,gi.SEGMENT5,gi.ITEM_CODE,gi.ITEM_DESC,gi.PART_NO,gi.UOM,gi.LONG_DESC,gi.IS_TOOL,
gi.IS_MACHINE,gi.IS_PART,gi.IS_REPLACEMENT_REQ,gi.IS_CEP_REQ,gi.IS_CONSUMABLE,gi.IS_ACTIVE,gi.MODEL,gi.PARENT_ID,gi.PARENT_VAL,gi.CREATED_BY,
gi.CREATION_DATE,gi.LAST_UPDATED_BY,gi.LAST_UPDATE_DATE,gi.CUR_QTY,gi.CUR_VALUE,gi.LAST_GRN_DATE,gi.LAST_GRN_NUM,gi.CUR_RATE,gi.LAST_GRN_RATE,
gi.LAST_GRN_QTY,gi.LAST_ISSUE_DATE,gi.LAST_ISSUE_QTY,gi.CHECK_MATERIAL_SHORTAGE,gi.MIN_QTY,gi.MAX_QTY,gi.RE_ORDER_LEVEL,gi.AVG_CONS,
gi.PRE_PROCESSING,gi.PROCESSING_TIME,gi.DELIVERY_TIME,gi.POST_PROCESSING,gi.LEAD_TIME,gi.OVER_RECEIPT_TOLERANCE,gi.LAST_PO_NO,gi.LAST_PO_RATE,
gi.SALES_RATE,gi.COST_RATE,gi.FINISHED_PRODUCT,gi.IS_WASTE,gi.GL_ASSET_ACC_ID,gi.GL_CONSUMPTION_NAT_ACC_ID,gi.GL_SERVICES_NAT_ACC_ID,
gi.WO_REQUIRED,gi.ISSUE_QTY_CHANGE_ALLOWED,gi.DESIGN_NAME,gi.DESIGN_STYLE,gi.PROCESS_NAME,gi.QUALITY,gi.CROCKING,gi.SHRINKING,gi.COLOUR_FASTNESS,
gi.COLOUR,gi.DIRECTION,gi.GREY_WIDTH,gi.READY_WIDTH,gi.ITEM_SIZE,gi.FINISHED_WEIGHT,gi.PACKING_INFORMATION,gi.STICHING_INSTRUCTION,gi.APPROVED_RATE,
gi.SALEABLE,gi.GL_COST_ACC_ID,gi.GL_SALE_ACC_ID,gi.FAST_MOVING,gi.LAST_ISSUE_NO,gi.ITEM_RANK,gi.DESIGN,gi.LOCATOR_ID,gi.IS_PURCHASABLE,
gi.IS_SEMI_FINISHED,gi.CUSTOMER_ARTICLE_NO,gi.INTERNAL_ARTICLE_NO,gi.LENGHT,gi.WIDTH,gi.HEIGHT)
select ni.ITEM_ID,ni.SEGMENT1,ni.SEGMENT2,ni.SEGMENT3,ni.SEGMENT4,ni.SEGMENT5,ni.ITEM_CODE,ni.ITEM_DESC,ni.PART_NO,ni.UOM,ni.LONG_DESC,ni.IS_TOOL,
ni.IS_MACHINE,ni.IS_PART,ni.IS_REPLACEMENT_REQ,ni.IS_CEP_REQ,ni.IS_CONSUMABLE,ni.IS_ACTIVE,ni.MODEL,ni.PARENT_ID,ni.PARENT_VAL,ni.CREATED_BY,
ni.CREATION_DATE,ni.LAST_UPDATED_BY,ni.LAST_UPDATE_DATE,ni.CUR_QTY,ni.CUR_VALUE,ni.LAST_GRN_DATE,ni.LAST_GRN_NUM,ni.CUR_RATE,ni.LAST_GRN_RATE,
ni.LAST_GRN_QTY,ni.LAST_ISSUE_DATE,ni.LAST_ISSUE_QTY,ni.CHECK_MATERIAL_SHORTAGE,ni.MIN_QTY,ni.MAX_QTY,ni.RE_ORDER_LEVEL,ni.AVG_CONS,
ni.PRE_PROCESSING,ni.PROCESSING_TIME,ni.DELIVERY_TIME,ni.POST_PROCESSING,ni.LEAD_TIME,ni.OVER_RECEIPT_TOLERANCE,ni.LAST_PO_NO,ni.LAST_PO_RATE,
ni.SALES_RATE,ni.COST_RATE,ni.FINISHED_PRODUCT,ni.IS_WASTE,ni.GL_ASSET_ACC_ID,ni.GL_CONSUMPTION_NAT_ACC_ID,ni.GL_SERVICES_NAT_ACC_ID,
ni.WO_REQUIRED,ni.ISSUE_QTY_CHANGE_ALLOWED,ni.DESIGN_NAME,ni.DESIGN_STYLE,ni.PROCESS_NAME,ni.QUALITY,ni.CROCKING,ni.SHRINKING,ni.COLOUR_FASTNESS,
ni.COLOUR,ni.DIRECTION,ni.GREY_WIDTH,ni.READY_WIDTH,ni.ITEM_SIZE,ni.FINISHED_WEIGHT,ni.PACKING_INFORMATION,ni.STICHING_INSTRUCTION,ni.APPROVED_RATE,
ni.SALEABLE,ni.GL_COST_ACC_ID,ni.GL_SALE_ACC_ID,ni.FAST_MOVING,ni.LAST_ISSUE_NO,ni.ITEM_RANK,ni.DESIGN,ni.LOCATOR_ID,ni.IS_PURCHASABLE,
ni.IS_SEMI_FINISHED,ni.CUSTOMER_ARTICLE_NO,ni.INTERNAL_ARTICLE_NO,ni.LENGHT,ni.WIDTH,ni.HEIGHT
from nbl.inv_items ni; 

select max(val_id) from inv_item_code_segment_values;
select max(item_id) from inv_items;
DROP SEQUENCE INV_ITEM_CODE_SEGMENT_VALUES_V;

CREATE SEQUENCE INV_ITEM_CODE_SEGMENT_VALUES_V
  START WITH 643
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_ITEMS_S;

CREATE SEQUENCE INV_ITEMS_S
  START WITH 2822
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;