SELECT DISTINCT RECEIPT_STATUS FROM AR_RECEIPTS;

select sum(sri.amount) from sm_sale_returns sr, sm_sale_return_items sri where SR.SR_ID=SRI.SR_ID and SR.CUSTOMER_ID = 2726;

select sum(SI.TOTAL_INVOICE_AMOUNT), sum(SI.INVOICE_ADJUSTED), sum(SI.INVOICE_BALANCE) --30127980.5, 2395909.5
from sm_sales_invoices si
where si.customer_id = 2726
--AND BRANCH_ID IS NULL
--AND SI.GL_VOUCHER_ID IN (SELECT VOUCHER_ID FROM GL_VOUCHER_ACCOUNTS)
--and SI.INVOICE_STATUS in ('APPROVED','CLOSED')  CREATED','CHECKED')
and si.company_id =23 and branch_id = '02'
--AND SI.INVOICE_DATE BETWEEN '01-JUN-13' AND '30-JUN-13'
;

SELECT DISTINCT INVOICE_STATUS FROM SM_SALES_INVOICES;

select sum(RI.ENTERED_AMOUNT)  ---30121065
from ar_receipts r, ar_receipt_invoices ri
where R.CUSTOMER_ID =2726 and R.RECEIPT_ID = RI.RECEIPT_ID AND R.RECEIPT_STATUS IN ('APPROVED','CLOSED')
AND R.VOUCHER_ID IN (SELECT VA.VOUCHER_ID FROM GL_VOUCHER_ACCOUNTS VA)
--and company_id =23 and branch_id = '02'
;

select * from ar_customers where customer_id = 2726

select sum(ADV.AMOUNT) from ar_advances adv where ADV.CUSTOMER_ID = 2726;

sm_sales_advances;

select --V.VOUCHER_ID, V.VOUCHER_NO, V.VOUCHER_TYPE,
sum(debit), sum(credit), sum(debit) - sum(credit) DIFF from gl_vouchers v, gl_voucher_accounts va
where v.voucher_id = va.voucher_id
--and V.MODULE_DOC_ID is null --18534390      17797565   736825
and va.account_id = 8579
AND company_id =23 and branch_id = '02'
AND V.VOUCHER_TYPE IN ('CRV','BRV') AND MODULE='AR' AND MODULE_DOC='SALE_INVOICE'
--GROUP BY V.VOUCHER_ID, V.VOUCHER_NO, V.VOUCHER_TYPE
;

SELECT MODULE_DOC_ID FROM GL_VOUCHERS
WHERE MODULE = 'AR' AND MODULE_DOC = 'SALE_INVOICE' AND COMPANY_ID = 23 AND BRANCH_ID = '02'
GROUP BY MODULE_DOC_ID                      --AR_INVOICE_TRANSFER
HAVING COUNT(MODULE_DOC_ID) > 1;

SELECT DISTINCT SI.INVOICE_STATUS FROM SM_SALES_INVOICES SI
WHERE SI.SALES_INVOICE_ID IN (SELECT RI.INVOICE_ID FROM AR_RECEIPT_INVOICES RI)
AND SI.COMPANY_ID = 23 AND SI.BRANCH_ID = '02';

SELECT SUM(VA.DEBIT), SUM(VA.CREDIT), V.MODULE, V.MODULE_DOC, V.MODULE_DOC_ID, V.VOUCHER_ID, V.VOUCHER_TYPE, V.VOUCHER_NO,V.VOUCHER_DATE
FROM GL_VOUCHERS V, GL_VOUCHER_ACCOUNTS VA       
WHERE V.VOUCHER_ID = VA.VOUCHER_ID AND VA.ACCOUNT_ID = 8579 AND VA.CREDIT>0--AND V.MODULE_DOC = 'RECEIPT'
AND V.COMPANY_ID = 23 AND V.BRANCH_ID = '02' AND V.STATUS IN ('APPROVED','CLOSED') --AND V.VOUCHER_TYPE IN ('BRV','CRV') 
AND V.MODULE_DOC_ID NOT IN (SELECT R.RECEIPT_ID FROM AR_RECEIPTS R WHERE R.RECEIPT_STATUS IN ('APPROVED','CLOSED'))
GROUP BY V.MODULE, V.MODULE_DOC, V.MODULE_DOC_ID, V.VOUCHER_ID, V.VOUCHER_TYPE, V.VOUCHER_NO,V.VOUCHER_DATE;

SELECT SUM(VA.DEBIT), SUM(VA.CREDIT) FROM GL_VOUCHERS V, GL_VOUCHER_ACCOUNTS VA       
WHERE V.VOUCHER_ID=VA.VOUCHER_ID AND VA.ACCOUNT_ID=8579 AND V.COMPANY_ID=23 AND V.BRANCH_ID='02' AND V.STATUS IN ('APPROVED','CLOSED')
AND V.MODULE_DOC_ID IN (SELECT R.RECEIPT_ID FROM AR_RECEIPTS R WHERE R.RECEIPT_STATUS IN ('APPROVED','CLOSED') AND R.CUSTOMER_ID = 2726);

SELECT SUM(VA.DEBIT),SUM(VA.CREDIT) FROM GL_VOUCHERS V,GL_VOUCHER_ACCOUNTS VA WHERE VA.ACCOUNT_ID=8579 AND V.COMPANY_ID=23
AND V.BRANCH_ID='02' AND V.VOUCHER_ID=VA.VOUCHER_ID AND V.STATUS IN ('APPROVED','CLOSED');

1,76,14,565  1,77,97,565   (receipt=1,70,64,565)+(sr=5241.5)=(total=17059323.5)              ;

SELECT SUM(RI.ENTERED_AMOUNT) FROM AR_RECEIPTS R, AR_RECEIPT_INVOICES RI WHERE R.RECEIPT_ID = RI.RECEIPT_ID 
AND R.CUSTOMER_ID = 2726 AND R.RECEIPT_STATUS IN ('APPROVED','CLOSED') AND COMPANY_ID = 23 AND BRANCH_ID='02';

select 17797565-17614565 diff from dual;

select sum(sri.amount) from sm_sale_returns sr, sm_sale_return_items sri where sr.sr_id=sri.sr_id and sr.customer_id=2726