--TRANSACTIONS
----General Ledger
DELETE FROM GL_VOUCHERS;
DELETE FROM GL_VOUCHER_ACCOUNTS;

DROP SEQUENCE GL_VOUCHER_ID_S;

CREATE SEQUENCE GL_VOUCHER_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
DROP SEQUENCE GL_VOUCHER_ACCOUNT_ID_S;

CREATE SEQUENCE GL_VOUCHER_ACCOUNT_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
----Account Receivables
DELETE FROM SM_SALES_INVOICES;
DELETE FROM SM_SALES_INVOICE_ITEMS;
DELETE FROM SM_SALES_EXPENSES;
DELETE FROM SM_SALES_ADVANCES;
DELETE FROM SM_SALES_INVOICE_COMMISIONS;
DELETE FROM AR_RECEIPT_INVOICES;

DROP SEQUENCE SM_SALES_INVOICE_ID_S;

CREATE SEQUENCE SM_SALES_INVOICE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


