DELETE FROM GL_VOUCHER_ACCOUNTS VA
WHERE VA.VOUCHER_ID = (SELECT I.GL_VOUCHER_ID FROM AP_INVOICES I WHERE I.INVOICE_ID = 1522);

DELETE FROM GL_VOUCHERS V
WHERE V.VOUCHER_ID = (SELECT I.GL_VOUCHER_ID FROM AP_INVOICES I WHERE I.INVOICE_ID = 1522);

DELETE FROM AP_INVOICE_LINES IL WHERE IL.INVOICE_ID = 1522;

DELETE FROM AP_INVOICES WHERE INVOICE_ID = 1522;