update sm_delivery_challans
set status = 'APPROVED'
where dc_id IN (SELECT DC_ID FROM SM_OGPS WHERE OGP_ID = :OGPID
                AND OGP_ID NOT IN (SELECT SALES_OGP_ID FROM SM_SALES_INVOICES WHERE SALES_OGP_ID = :OGPID));

DELETE FROM SM_OGP_ITEMS WHERE OGP_ID = :OGPID
AND OGP_ID NOT IN (SELECT SALES_OGP_ID FROM SM_SALES_INVOICES WHERE SALES_OGP_ID = :OGPID);

DELETE FROM SM_OGPS WHERE OGP_ID = :OGPID
AND OGP_ID NOT IN (SELECT SALES_OGP_ID FROM SM_SALES_INVOICES WHERE SALES_OGP_ID = :OGPID);