DELETE FROM GL_VOUCHER_ACCOUNTS WHERE VOUCHER_ID IN (SELECT GL_VOUCHER_ID FROM AP_INVOICES where INVOICE_TYPE = 'COTTON');
DELETE FROM GL_VOUCHERS WHERE VOUCHER_ID IN (SELECT GL_VOUCHER_ID FROM AP_INVOICES where INVOICE_TYPE = 'COTTON');
DELETE FROM AP_INVOICE_LINES WHERE INVOICE_ID IN (SELECT INVOICE_ID FROM AP_INVOICES where INVOICE_TYPE = 'COTTON');
delete from ap_invoices where INVOICE_TYPE = 'COTTON';
--CHECK BEFORE EXECUTING
SELECT MAX(INVOICE_ID) FROM AP_INVOICES;
DROP SEQUENCE AP_INVOICE_ID_S;
CREATE SEQUENCE AP_INVOICE_ID_S
  START WITH 14909
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
DELETE FROM INV_ITEM_COMPANIES;
DELETE FROM INV_ITEM_COMPANY_STORES;
DELETE FROM INV_ITEM_COMPANY_LOT;
DELETE FROM GL_VOUCHERS WHERE VOUCHER_ID IN (SELECT VOUCHER_ID FROM INV_GRN_COTTONS);
DELETE FROM GL_VOUCHER_ACCOUNTS WHERE VOUCHER_ID IN (SELECT VOUCHER_ID FROM INV_GRN_COTTONS);
DELETE FROM INV_GRN_COTTONS;
DROP SEQUENCE GRN_ID_S;
CREATE SEQUENCE GRN_ID_S
  START WITH 1
  MAXVALUE 99999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DELETE FROM inv_lots WHERE COTTON = 'C';
DELETE FROM INV_IRN_COTTONS;
DROP SEQUENCE INV_IRN_S;
CREATE SEQUENCE INV_IRN_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

delete from INV_IGP_COTTONS;
DROP SEQUENCE IGP_ID_S;
CREATE SEQUENCE IGP_ID_S
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

delete from INV_COTTON_CONTRACTS;
alter table INV_COTTON_CONTRACTS
modify (NO_OF_BALES     number(16,4),
        MOISTURE_PER    number(16,4),
        TRASH_PER       number(16,4),
        COMMISION_PER   number(16,4),
        BALANCE         number(16,4)
        );
DROP SEQUENCE CONTRACT_ID_S;
CREATE SEQUENCE CONTRACT_ID_S
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;