Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '02', 784, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '03', 784, 'N', 1,sysdate, 1, sysdate);   
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '04', 784, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '05', 784, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '06', 784, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '07', 784, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '08', 784, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '09', 784, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '10', 784, 'N', 1,sysdate, 1, sysdate);

Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '02', 785, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '03', 785, 'N', 1,sysdate, 1, sysdate);   
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '04', 785, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '05', 785, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '06', 785, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '07', 785, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '08', 785, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '09', 785, 'N', 1,sysdate, 1, sysdate);
   
Insert into SYS_USER_BRANCHES
   (USER_BRANCH_ID,BRANCH_ID,USER_ID,VIEW_OPT,CREATED_BY,CREATION_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE)
 Values
   (SYS_USER_BRANCH_ID_S.nextval, '10', 785, 'N', 1,sysdate, 1, sysdate);