delete from inv_adjs;
delete from inv_mirs;
delete from inv_sins;
delete from inv_sin_mirs;
delete from inv_item_companies;
delete from inv_item_company_stores;
delete from INV_CASH_PURCHASE;
delete from INV_CASH_PURCHASE_ITEMS;
DELETE FROM INV_INDENTS;
DELETE FROM INV_INDENTS_CHECKED;
DELETE FROM INV_CS;
DELETE FROM INV_CS_ITEMS;
DELETE FROM INV_CS_ITEMS_VENDERS;
DELETE FROM INV_POS;
DELETE FROM INV_PO_ITEMS;
DELETE FROM INV_PO_ITEM_SHIPMENTS;
DELETE FROM INV_PO_IMAGES;
DELETE FROM INV_PO_DELIVERY_TERMS;
DELETE FROM INV_IGPS;
DELETE FROM INV_IGP_ITEMS;
DELETE FROM INV_IRNS;
DELETE FROM INV_IRN_ITEMS;
DELETE FROM INV_GRNS;
DELETE FROM INV_GRN_ITEMS;
DELETE FROM INV_ITEMS;
DELETE FROM INV_ITEM_categorieS;
DELETE FROM INV_ITEM_sub_categorieS;
DELETE FROM INV_FTNS;
DELETE FROM INV_FTN_ITEMS;
DELETE FROM INV_ITEM_COMPANIES;
DELETE FROM INV_ITEM_COMPANY_ORDERS;
DELETE FROM INV_ITEM_COMPANY_STORES;
DELETE FROM INV_MIRS;
DELETE FROM INV_MRRS;
DELETE FROM INV_PURCHASE_RETURN_ITEMS;
DELETE FROM INV_PURCHASE_RETURNS;
DELETE FROM INV_SINS;
DELETE FROM INV_SIN_MIRS;
DELETE FROM INV_SRN_MRRS;
DELETE FROM INV_SRNS;
DELETE FROM INV_STORE_TRANSFER_ITEMS;
DELETE FROM INV_STORE_TRANSFERS;
DELETE FROM INV_STORES;
DELETE FROM INV_TERM_SETS ;
DELETE FROM INV_TERM_SETS_TERMS;
DELETE FROM INV_TERMS;
DELETE FROM INV_VENDORS;
DELETE FROM INV_VENDOR_PERSONS;
DELETE FROM INV_VENDOR_ITEMS;
DELETE FROM INV_GRN_COTTONS;
DELETE FROM INV_IGP_COTTONS;
DELETE FROM INV_IRN_COTTONS;
DELETE FROM INV_LOTS;
DELETE FROM INV_ITEM_COMPANY_LOT;
DELETE FROM INV_COTTON_CONTRACTS;

delete from INV_BRANCH_TRANSFER_ITEMS;
delete from INV_BRANCH_TRANSFERS;
delete from INV_ITEM_CATEGORY_PARAMETERS;
delete from INV_ITEM_CODE_SEGMENT_VALUES;
delete from INV_ITEM_DESRIPTIONS;
delete from INV_ITEM_LOCATORS;
delete from INV_ITEM_PARAMETER_VALUES;
delete from INV_ITEM_PARAMETERS;
delete from INV_ITEMS_PARAMETERS;
delete from INV_LOCATORS;
delete from INV_PO_MANUAL_ITEMS;
delete from INV_PO_MANUALS;
delete from INV_SALES_PERSONS;
delete from INV_SIGP_ITEMS;
delete from INV_SIGPS;
delete from INV_SOGP_ITEMS;
delete from INV_SOGPS;
delete from INV_USER_TRANSACTIONS;
delete from INV_VENDOR_SERVICE_ITEMS;

DROP SEQUENCE INV_ADJ_S;
DROP SEQUENCE INV_MIR_S;
DROP SEQUENCE INV_CASH_PURCHASE_S;
DROP SEQUENCE INV_SIN_S;
DROP SEQUENCE INV_SIN_MIR_S;
DROP SEQUENCE INV_ITEMS_COMP_S;
DROP SEQUENCE INV_ITEM_COMP_STORE_ID_S;
DROP SEQUENCE INV_INDENT_S;
DROP SEQUENCE INV_CS_ITEMS_S;
DROP SEQUENCE INV_CS_ITEMS_VENDERS_S;
DROP SEQUENCE INV_CS_S;
DROP SEQUENCE INV_PO_S;
DROP SEQUENCE INV_PO_PT_ID_S;
DROP SEQUENCE INV_PO_ITEM_SHIPMENTS_S;
DROP SEQUENCE INV_PO_ITEM_S;
DROP SEQUENCE INV_IGP_S;
DROP SEQUENCE INV_IGP_ITEMS_S;
DROP SEQUENCE INV_IRN_IMPORT_CHARGE_ID_S;
DROP SEQUENCE INV_IRN_ITEM_S;
DROP SEQUENCE INV_IRN_S;
DROP SEQUENCE INV_GRN_S;
DROP SEQUENCE INV_GRN_ITEMS_S;
DROP SEQUENCE INV_GRN_ITEM_LOCATORS_S;
DROP SEQUENCE INV_GRN_ITEM_LOCATOR_S;
DROP SEQUENCE INV_ITEM_ID_S;
DROP SEQUENCE INV_ITEM_CATEGORY_ID_S;
DROP SEQUENCE INV_ITEM_SUB_CATEGORY_ID_S;
DROP SEQUENCE INV_FTN_ID_S;
DROP SEQUENCE INV_FTN_ITEM_ID_S;
DROP SEQUENCE INV_ITEM_COMP_ORDER_ID_S;
DROP SEQUENCE INV_ITEM_COMP_STORE_ID_S;
DROP SEQUENCE INV_MRN_ID_S;
DROP SEQUENCE INV_MRN_ITEM_ID_S;
DROP SEQUENCE INV_MRR_S;
DROP SEQUENCE INV_PR_ID_S;
DROP SEQUENCE INV_PR_ITEM_ID_S;
DROP SEQUENCE INV_STORE_TRANSFER_ITEM_S;
DROP SEQUENCE INV_STORE_TRANSFER_S;
DROP SEQUENCE INV_TERM_ID_S;
DROP SEQUENCE INV_TERM_SET_ID_S;
DROP SEQUENCE INV_TERM_SETS_TERM_ID_S;
DROP SEQUENCE INV_VENDOR_ID_S;
DROP SEQUENCE INV_VENDOR_PERSON_ID_S;
DROP SEQUENCE INV_VENDOR_PERSON_ID_S;


CREATE SEQUENCE INV_ADJ_S START WITH 1;
CREATE SEQUENCE INV_MIR_S START WITH 1;
CREATE SEQUENCE INV_VENDOR_PERSON_ID_S  START WITH 1;
CREATE SEQUENCE INV_VENDOR_ID_S   START WITH 1;
CREATE SEQUENCE INV_VENDOR_PERSON_ID_S   START WITH 1;
CREATE SEQUENCE INV_TERM_SETS_TERM_ID_S   START WITH 1;
CREATE SEQUENCE INV_TERM_SET_ID_S   START WITH 1;
CREATE SEQUENCE INV_TERM_ID_S   START WITH 1;
CREATE SEQUENCE INV_STORE_TRANSFER_S   START WITH 1;
CREATE SEQUENCE INV_STORE_TRANSFER_ITEM_S   START WITH 1;
CREATE SEQUENCE INV_MRR_S   START WITH 1;
CREATE SEQUENCE INV_PR_ID_S   START WITH 1;
CREATE SEQUENCE INV_PR_ITEM_ID_S   START WITH 1;
CREATE SEQUENCE INV_MRN_ITEM_ID_S   START WITH 1;
CREATE SEQUENCE INV_MRN_ID_S  START WITH 1;
CREATE SEQUENCE INV_ITEM_COMP_ORDER_ID_S   START WITH 1;
CREATE SEQUENCE INV_ITEM_COMP_STORE_ID_S  START WITH 1;
CREATE SEQUENCE INV_FTN_ID_S START WITH 1;
CREATE SEQUENCE INV_FTN_ITEM_ID_S   START WITH 1
CREATE SEQUENCE INV_CASH_PURCHASE_S   START WITH 1;
CREATE SEQUENCE INV_SIN_S START WITH 1;
CREATE SEQUENCE INV_SIN_MIR_S START WITH 1;
CREATE SEQUENCE INV_ITEMS_COMP_S START WITH 1;
CREATE SEQUENCE INV_ITEM_COMP_STORE_ID_S START WITH 1;
CREATE SEQUENCE INV_INDENT_S START WITH 1;
CREATE SEQUENCE INV_CS_ITEMS_S START WITH 1;
CREATE SEQUENCE INV_CS_ITEMS_VENDERS_S START WITH 1;
CREATE SEQUENCE INV_CS_S START WITH 1;
CREATE SEQUENCE INV_PO_S START WITH 1;
CREATE SEQUENCE INV_PO_PT_ID_S START WITH 1;
CREATE SEQUENCE INV_PO_ITEM_SHIPMENTS_S START WITH 1;
CREATE SEQUENCE INV_PO_ITEM_S START WITH 1;
CREATE SEQUENCE INV_IGP_S START WITH 1;
CREATE SEQUENCE INV_IGP_ITEMS_S START WITH 1;
CREATE SEQUENCE INV_IRN_IMPORT_CHARGE_ID_S START WITH 1;
CREATE SEQUENCE INV_IRN_ITEM_S START WITH 1;
CREATE SEQUENCE INV_IRN_S START WITH 1;
CREATE SEQUENCE INV_GRN_S START WITH 1;
CREATE SEQUENCE INV_GRN_ITEMS_S START WITH 1;
CREATE SEQUENCE INV_GRN_ITEM_LOCATORS_S START WITH 1;
CREATE SEQUENCE INV_GRN_ITEM_LOCATOR_S START WITH 1;
CREATE SEQUENCE INV_ITEM_CATEGORY_ID_S START WITH 1;
CREATE SEQUENCE INV_ITEM_SUB_CATEGORY_ID_S START WITH 1;
CREATE SEQUENCE INV_ITEM_ID_S  START WITH 1;

delete from HR_ATT_LOG;
delete from ATT;
delete from HR_ATT_MANNUALS;
delete from HR_PAYROLL_EMPLOYEE_BREAKUPS;
delete from HR_PAYROLL_VOUCHERS;
delete from HR_PAYROLLS;
delete from HR_PERFORMANCE_CATEGORIES;
delete from HR_PERFORMANCE_CRIT_CAT_DETAIL;
delete from HR_PERFORMANCE_CRITERIA;
delete from HR_PF_LEDGERS;
delete from HR_REST_CHANGES;
delete from HR_ROUSTER_GROUP_SCHEDULES;
delete from HR_ROUSTERS;
delete from HR_SHIFT_CHANGES;
delete from HR_SHORT_LEAVES;
delete from HR_SOCIAL_SECURITY_LEDGERS;
delete from HR_SWAP_RECORDS;
delete from HR_SWAP_UPLOAD_BATCHES;

delete from GL_BANKS;
delete from GL_CHART_OF_ACCOUNTS;
delete from GL_CONTROL_ACCOUNTS where record_level <>1;
delete from GL_COST_CENTERS;
delete from GL_SUB_ACCOUNT_CODES;
delete from GL_VOUCHER_ACCOUNTS;
delete from GL_VOUCHERS;

DROP SEQUENCE GL_ACCOUNT_ID_S;
DROP SEQUENCE GL_BANKS_ID_S;
DROP SEQUENCE GL_CONTROL_ACC_ID_S;
DROP SEQUENCE GL_COST_CENTER_ID_S;
DROP SEQUENCE GL_SUB_ACCOUNT_CODE_S;
DROP SEQUENCE GL_VOUCHER_ACCOUNT_ID_S;
DROP SEQUENCE GL_VOUCHER_ID_S;

CREATE SEQUENCE GL_ACCOUNT_ID_S START WITH 1;
CREATE SEQUENCE GL_BANKS_ID_S START WITH 1;
CREATE SEQUENCE GL_CONTROL_ACC_ID_S START WITH 10;
CREATE SEQUENCE GL_COST_CENTER_ID_S START WITH 1;
CREATE SEQUENCE GL_SUB_ACCOUNT_CODE_S START WITH 1;
CREATE SEQUENCE GL_VOUCHER_ACCOUNT_ID_S START WITH 1;
CREATE SEQUENCE GL_VOUCHER_ID_S START WITH 1;


delete from HR_ATT_LOG;
delete from ATT;
delete from HR_ATT_MANNUALS;
delete from HR_ATTENDANCE_DATES;
delete from HR_ATTENDANCES;
delete from HR_DEDUCTION_EMPS;
delete from HR_DEDUCTIONS;
delete from HR_EMP_ADVANCES;
delete from HR_EMP_EXPERIENCES;
delete from HR_EMP_FAMILIES;
delete from HR_EMP_JOB_DESCRIPTIONS;
delete from HR_EMP_JOIN_BREAKUPS;
delete from HR_EMP_JOIN_RESIGNS;
delete from HR_EMP_LEAVE_TYPES;
delete from HR_EMP_LEAVES;
delete from HR_EMP_REINSTATES;
delete from HR_EMP_SALARY_BREAKUPS;
delete from HR_EMPLOYEES;
delete from HR_EMPLOYEES_TYPES;
delete from HR_EMPLOYEES_TYPES_PERIODS;
delete from HR_EOBI_LEDGERS;
delete from HR_FIXED_DEDUCTIONS;
delete from HR_GAZETED_HOLIDAYS;
delete from HR_INC_REQ_EMPS;
delete from HR_INC_REQS;
delete from HR_INCENTIVE_EMPS;
delete from HR_INCENTIVES;
delete from HR_INCREMENT_EMPS;
delete from HR_INCREMENTS;
delete from HR_JOB_DESCRIPTIONS;
delete from HR_LOAN_SCHEDUALES;
delete from HR_LOANS;
delete from HR_OT_REQ_EMPS;
delete from HR_OT_REQS;
delete from HR_OTS;
delete from HR_PAYROLL_VOUCHERS;
delete from HR_PAYROLLS;
delete from HR_REST_CHANGES;
delete from HR_ROUSTER_GROUP_SCHEDULES;
delete from HR_ROUSTERS;
delete from HR_SHIFT_CHANGES;
delete from HR_SOCIAL_SECURITY_LEDGERS;
delete from HR_ATT_LOG_1;
delete from HR_ATTENDANCES;
delete from HR_DEDUCTION_EMPS;
delete from HR_DEDUCTIONS;
delete from HR_EMP_EXPERIENCES;
delete from HR_EMP_FAMILIES;
delete from HR_EMP_JOIN_BREAKUPS;
delete from HR_EMP_JOIN_RESIGNS;
delete from HR_EMP_LEAVES;
delete from HR_EMP_QUALIFICATIONS;
delete from HR_EMP_REINSTATES;
delete from HR_EMP_SALARY_BREAKUPS;
delete from HR_EMPLOYEES;
delete from HR_EMPLOYEES_TYPES;
delete from HR_EMPLOYEES_TYPES_PERIODS;
delete from HR_EOBI_LEDGERS;
delete from HR_FIXED_DEDUCTIONS;
delete from HR_GAZETED_HOLIDAYS;
delete from HR_INCENTIVE_EMPS;
delete from HR_INCENTIVES;
delete from HR_INCREMENT_EMPS;
delete from HR_INCREMENTS;
delete from HR_JOB_DESCRIPTIONS;
delete from HR_LEAVE_TYPE_GROUPS;
delete from HR_LOAN_SCHEDUALES;
delete from HR_LOANS;
delete from HR_SALARY_ADVANCE_EMPS;
delete from HR_SALARY_ADVANCES;
delete from HR_SHIFTS;

DROP SEQUENCE  HR_ATT_MANNUALS_ID_S;
DROP SEQUENCE  HR_ATTENDANCE_DATE_ID_S;
DROP SEQUENCE  HR_ATTENDANCE_ID_S;
DROP SEQUENCE  HR_DEDUCTION_EMP_ID_S;
DROP SEQUENCE  HR_DEDUCTION_ID_S;
DROP SEQUENCE  HR_EMP_ADVANCE_ID_S;
DROP SEQUENCE  HR_EMP_EXPERIENCE_ID_S;
DROP SEQUENCE  HR_EMP_FAMILY_ID_S;
DROP SEQUENCE  HR_EMP_ID_S;
DROP SEQUENCE  HR_EMP_JOB_DESCRIPTION_ID_S;
DROP SEQUENCE  HR_EMP_JOIN_BREAKUP_ID_S;
DROP SEQUENCE  HR_EMP_JR_ID_S;
DROP SEQUENCE  HR_EMP_LEAVE_ID_S;
DROP SEQUENCE  HR_EMP_LEAVE_TYPE_ID_S;
DROP SEQUENCE  HR_EMP_QUALIFICATION_ID_S;
DROP SEQUENCE  HR_EMP_REINSTATE_ID_S;
DROP SEQUENCE  HR_EMP_SALARY_BREAKUP_ID_S;
DROP SEQUENCE HR_EMP_TYPE_ID_S;
DROP SEQUENCE  HR_EOBI_LEDGER_ID_S;
DROP SEQUENCE  HR_FIXED_DEDUCTION_ID_S;
DROP SEQUENCE  HR_GAZETED_HOLIDAY_ID_S;
DROP SEQUENCE  HR_INCENTIVE_EMP_ID_S;
DROP SEQUENCE  HR_INCENTIVE_ID_S;
DROP SEQUENCE  HR_INCREMENT_EMP_ID_S;
DROP SEQUENCE  HR_INCREMENT_ID_S;
DROP SEQUENCE HR_LEAVE_TYPE_GROUP_ID_S;
DROP SEQUENCE  HR_LOAN_ID_S;
DROP SEQUENCE  HR_LOAN_SCHEDUALE_ID_S;
DROP SEQUENCE  HR_OT_ID_S;
DROP SEQUENCE  HR_OT_REQ_EMP_ID_S;
DROP SEQUENCE  HR_OT_REQ_ID_S;
DROP SEQUENCE  HR_PAYROLL_EMP_BREAKUP_ID_S;
DROP SEQUENCE  HR_PAYROLL_ID_S;
DROP SEQUENCE  HR_PAYROLL_VOUCHER_ID_S;
DROP SEQUENCE  HR_PF_LEDGER_ID_S;
DROP SEQUENCE  HR_REST_CHANGE_ID_S;
DROP SEQUENCE  HR_REST_CHANGE_S;
DROP SEQUENCE  HR_ROUSTER_GROUP_SCHEDULE_ID_S;
DROP SEQUENCE  HR_ROUSTER_ID_S;
DROP SEQUENCE  HR_SHIFT_CHANGE_ID_S;
DROP SEQUENCE  HR_SOCIAL_SECURITY_LEDGER_ID_S;

CREATE SEQUENCE  HR_ATT_MANNUALS_ID_S START WITH 1;
CREATE SEQUENCE  HR_ATTENDANCE_DATE_ID_S START WITH 1;
CREATE SEQUENCE HR_LEAVE_TYPE_GROUP_ID_S   START WITH 1;
CREATE SEQUENCE HR_EMP_TYPE_ID_S   START WITH 1;
CREATE SEQUENCE  HR_ATTENDANCE_ID_S START WITH 1;
CREATE SEQUENCE  HR_DEDUCTION_EMP_ID_S START WITH 1;
CREATE SEQUENCE  HR_DEDUCTION_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_ADVANCE_ID_S START WITH 1;
CREATE SEQUENCE HR_EMP_QUALIFICATION_ID_S   START WITH 1;
CREATE SEQUENCE  HR_EMP_EXPERIENCE_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_FAMILY_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_JOB_DESCRIPTION_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_JOIN_BREAKUP_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_JR_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_LEAVE_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_LEAVE_TYPE_ID_S;
CREATE SEQUENCE  HR_EMP_QUALIFICATION_ID_S START WITH 1;
CREATE SEQUENCE  HR_EMP_SALARY_BREAKUP_ID_S START WITH 1;
CREATE SEQUENCE  HR_EOBI_LEDGER_ID_S START WITH 1;
CREATE SEQUENCE  HR_FIXED_DEDUCTION_ID_S START WITH 1;
CREATE SEQUENCE  HR_GAZETED_HOLIDAY_ID_S START WITH 1;
CREATE SEQUENCE  HR_INCENTIVE_EMP_ID_S START WITH 1;
CREATE SEQUENCE  HR_INCENTIVE_ID_S START WITH 1;
CREATE SEQUENCE  HR_INCREMENT_EMP_ID_S START WITH 1;
CREATE SEQUENCE  HR_INCREMENT_ID_S START WITH 1;
CREATE SEQUENCE  HR_LOAN_ID_S START WITH 1;
CREATE SEQUENCE  HR_LOAN_SCHEDUALE_ID_S START WITH 1;
CREATE SEQUENCE  HR_OT_ID_S START WITH 1;
CREATE SEQUENCE  HR_OT_REQ_EMP_ID_S START WITH 1;
CREATE SEQUENCE  HR_OT_REQ_ID_S START WITH 1;
CREATE SEQUENCE  HR_PAYROLL_EMP_BREAKUP_ID_S START WITH 1;
CREATE SEQUENCE  HR_PAYROLL_ID_S START WITH 1;
CREATE SEQUENCE  HR_PAYROLL_VOUCHER_ID_S START WITH 1;
CREATE SEQUENCE  HR_PF_LEDGER_ID_S START WITH 1;
CREATE SEQUENCE  HR_REST_CHANGE_ID_S START WITH 1;
CREATE SEQUENCE  HR_REST_CHANGE_S START WITH 1;
CREATE SEQUENCE  HR_ROUSTER_GROUP_SCHEDULE_ID_S START WITH 1;
CREATE SEQUENCE  HR_ROUSTER_ID_S START WITH 1;
CREATE SEQUENCE  HR_SHIFT_CHANGE_ID_S START WITH 1;
CREATE SEQUENCE  HR_SOCIAL_SECURITY_LEDGER_ID_S START WITH 1;

delete from  SM_SALE_ORDERS;
delete from SM_SALE_ORDER_ITEMS;
delete from SM_PRODUCTION_ORDERS;
delete from SM_PRODUCTION_ORDER_ITEMS;
delete from PR_BOM_LINES;
delete from  PR_BOM_ORDER_ITEMS;
delete from PR_BOM_ORDER_MATERIALS;
delete from PR_BOM_ORDERS;
delete from PR_ORDER_ISSUANCE_ITEMS;
delete from PR_ORDER_PUR_REQUEST_ITEMS;
delete from PR_PROJECTION_ITEMS;
delete from PR_PROJECTION_MATERIALS;
delete from PR_PROJECTIONS;
------------------------------------
delete from AP_INVOICE_LINES;
delete from AP_INVOICES;
delete from  AR_CUSTOMER_PERSONS;
delete from AR_CUSTOMER_SHIPMENT_INFOS;
delete from AR_CUSTOMERS;
delete from AR_RECEIPT_INVOICES;
delete from AR_RECEIPTS;


delete from PR_ORDER_PUR_REQUESTS;
delete from PR_PRODUCTION_PLANNING;
delete from PR_PRODUCTION_PLANNING_ITEMS;
delete from PR_PRODUCTION_SCHEDULE_ITEMS;
delete from PR_PRODUCTION_SCHEDULES;
DELETE FROM SM_DELIVERY_ORDER_ITEMS;
DELETE FROM SM_DELIVERY_ORDERS;
DELETE FROM SM_SALE_ORDER_AGENTS;
delete from SM_DELIVERY_CHALLAN_ITEM_POS;
delete from SM_DELIVERY_CHALLAN_ITEMS;
delete from SM_DELIVERY_CHALLANS;
delete from SM_OGP_ITEMS;
delete from SM_OGPS;
delete from SM_SALE_RETURN_ITEMS;
delete from SM_SALE_RETURNS;
delete from SM_SALES_INVOICE_COMMISIONS;
delete from SM_SALES_INVOICE_ITEMS;
delete from SM_SALES_INVOICES;
delete from SQL_ITEMS;
delete from SVR_IGP_CHECKED;
delete from SVR_ROGP_IGP_ITEMS;
delete from SVR_ROGP_IGPS;
delete from SVR_ROGP_ITEMS;
delete from SVR_ROGP_REQS;
delete from SVR_ROGPS;
delete from SYS_USER_BRANCHES where branch_id <>'01';

delete from SYS_LOGOS;
delete from SYS_USER_LOGINS;
delete from SYS_USER_PICTURES;
delete from SYS_USER_COMPANIES where user_id <> 1;
delete from sys_users where user_id <> 1;
delete from sys_user_scr_options where  user_id <> 1;
update sys_user_scr_options set opt='Y';

delete from  SYS_USER_COMPANIES where company_id<>1;


DROP SEQUENCE SYS_USER_LOGIN_ID_S;
CREATE SEQUENCE SYS_USER_LOGIN_ID_S START WITH 1;


delete from AP_ADVANCES;
delete from AP_INVOICE_ADVANCES;
delete from AP_PAYMENT_EXPENSES;
delete from AP_PAYMENT_INVOICES;
delete from AP_PAYMENTS;
delete from CGS_COST_TRANSFERS;

delete from GL_NATURAL_ACCOUNTS;

delete from HR_CPL_EMPS;
delete from HR_CPLS;
delete from HR_EMP_CONFIRMATIONS;
delete from HR_EMP_LEAVE_BALANCES;
delete from HR_EMP_LEAVE_OPENINGS;
delete from HR_EMP_STRENGTHS;
delete from HR_ENCASHMENT_LEAVES;
delete from HR_ENCASHMENTS;
delete from HR_FINAL_SETTLEMENT_DEDUCTIONS;
delete from HR_FINAL_SETTLEMENT_INCENTIVES;
delete from HR_FINAL_SETTLEMENTS;
delete from HR_ITEM_RATES;
delete from HR_MESS_ATTENDANCES;
delete from HR_MESS_MENU;
delete from HR_PIECE_RATE_EMPS;
delete from HR_PIECE_RATE_PAYROLL_BREAKUPS;
delete from HR_PIECE_RATE_PAYROLLS;
delete from HR_PIECE_RATES;
delete from INV_COST_DEPT;
delete from INV_IGP_CHECKED;
delete from TEMP_LEAVE_BALANCES;

delete from SYS_LOGOS;
delete from SYS_USER_LOGINS;
delete from SYS_USER_PICTURES;
delete from SYS_USER_COMPANIES where user_id <> 1;
delete from sys_users where user_id <> 1;
delete from sys_user_scr_options where  user_id <> 1;
update sys_user_scr_options set opt='Y';

DROP SEQUENCE SYS_USER_LOGIN_ID_S;
CREATE SEQUENCE SYS_USER_LOGIN_ID_S START WITH 1;

Insert into INV_ITEM_CODE_SEGMENT_VALUES
   (VAL_ID, SEGMENT_ID, SEGMENT_VAL, SEGMENT_VAL_DESC, PARENT_VAL, 
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (0, 0, null, 'Item Chart', null, 
    1, sysdate, 1, sysdate);
    
DROP SEQUENCE AP_ADVANCE_ID_S;

CREATE SEQUENCE AP_ADVANCE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE AP_INVOICE_ADVANCE_ID_S;

CREATE SEQUENCE AP_INVOICE_ADVANCE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AP_INVOICE_ID_S;

CREATE SEQUENCE AP_INVOICE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AP_INVOICE_LINE_ID_S;

CREATE SEQUENCE AP_INVOICE_LINE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AP_PAYMENT_EXPENSE_ID_S;

CREATE SEQUENCE AP_PAYMENT_EXPENSE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AP_PAYMENT_ID_S;

CREATE SEQUENCE AP_PAYMENT_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AP_PAYMENT_INVOICE_ID_S;

CREATE SEQUENCE AP_PAYMENT_INVOICE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AR_ADVANCE_ID_S;

CREATE SEQUENCE AR_ADVANCE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP SEQUENCE AR_ADVANCE_ID_S;

CREATE SEQUENCE AR_ADVANCE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP SEQUENCE AR_CUSTOMER_BILLING_INF_S;

CREATE SEQUENCE AR_CUSTOMER_BILLING_INF_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE AR_CUSTOMER_ID;

CREATE SEQUENCE AR_CUSTOMER_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE AR_CUSTOMER_ID_S;

CREATE SEQUENCE AR_CUSTOMER_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE AR_CUSTOMER_PERSON_ID_S;

CREATE SEQUENCE AR_CUSTOMER_PERSON_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AR_CUSTOMER_SHIPMENT_INF_S;

CREATE SEQUENCE AR_CUSTOMER_SHIPMENT_INF_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE AR_RECEIPT_ID_S;

CREATE SEQUENCE AR_RECEIPT_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE AR_RECEIPT_INVOICE_ID_S;

CREATE SEQUENCE AR_RECEIPT_INVOICE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE GRN_ID_S;

CREATE SEQUENCE GRN_ID_S
  START WITH 1
  MAXVALUE 99999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE HR_ATT_LOG_ID_S;

CREATE SEQUENCE HR_ATT_LOG_ID_S
  START WITH 1
  MAXVALUE 99999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE HR_EMP_LEAVE_BALANCE_ID_S;

CREATE SEQUENCE HR_EMP_LEAVE_BALANCE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE HR_EMP_LEAVE_OPENING_ID_S;

CREATE SEQUENCE HR_EMP_LEAVE_OPENING_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE HR_EMP_SHORT_LEAVE_ID_S;

CREATE SEQUENCE HR_EMP_SHORT_LEAVE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE HR_EMP_STRENGTH_ID_S;

CREATE SEQUENCE HR_EMP_STRENGTH_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE HR_SETTLEMENT_DED_ID_S;

CREATE SEQUENCE HR_SETTLEMENT_DED_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE HR_SETTLEMENT_ID_S;

CREATE SEQUENCE HR_SETTLEMENT_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE HR_SETTLEMENT_LEAVE_ID_S;

CREATE SEQUENCE HR_SETTLEMENT_LEAVE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE IGP_ID_S;

CREATE SEQUENCE IGP_ID_S
  START WITH 1
  MAXVALUE 99999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE IMP_PERFORMA_ID_S;

CREATE SEQUENCE IMP_PERFORMA_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_BRANCH_TRANSFER_ITEM_S;

CREATE SEQUENCE INV_BRANCH_TRANSFER_ITEM_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_BRANCH_TRANSFER_S;

CREATE SEQUENCE INV_BRANCH_TRANSFER_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_CHALLAN_ID_S;

CREATE SEQUENCE INV_CHALLAN_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE INV_CHALLAN_ITEM_ID_S;

CREATE SEQUENCE INV_CHALLAN_ITEM_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE INV_ITEMS_S;

CREATE SEQUENCE INV_ITEMS_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_LOT_ID_S;

CREATE SEQUENCE INV_LOT_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE INV_PO_MANUAL_ITEM_S;

CREATE SEQUENCE INV_PO_MANUAL_ITEM_S
  START WITH 1
  MAXVALUE 99999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_PO_MANUAL_S;

CREATE SEQUENCE INV_PO_MANUAL_S
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_SALES_LC_EXPENSE_ID_S;

CREATE SEQUENCE INV_SALES_LC_EXPENSE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_SALES_ORDER_ITEM_ID_S;

CREATE SEQUENCE INV_SALES_ORDER_ITEM_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_SERIAL_ID_S;

CREATE SEQUENCE INV_SERIAL_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE INV_SIN_MIR_LOCATOR_S;

CREATE SEQUENCE INV_SIN_MIR_LOCATOR_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE INV_SOGP_ITEM_S;

CREATE SEQUENCE INV_SOGP_ITEM_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE INV_SOGP_S;

CREATE SEQUENCE INV_SOGP_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE OE_ORDER_AGENT_ID_S;

CREATE SEQUENCE OE_ORDER_AGENT_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_DELIVERY_CHALLAN_ITEM_S;

CREATE SEQUENCE SM_DELIVERY_CHALLAN_ITEM_S
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_DELIVERY_CHALLAN_S;

CREATE SEQUENCE SM_DELIVERY_CHALLAN_S
  START WITH 1
  MAXVALUE 99999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_DELIVERY_ORDER_ITEM_S;

CREATE SEQUENCE SM_DELIVERY_ORDER_ITEM_S
  START WITH 1
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_DELIVERY_ORDER_S;

CREATE SEQUENCE SM_DELIVERY_ORDER_S
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_IGP_ID_S;

CREATE SEQUENCE SM_IGP_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE SM_IGP_ITEM_ID_S;

CREATE SEQUENCE SM_IGP_ITEM_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE SM_OGP_ITEM_S;

CREATE SEQUENCE SM_OGP_ITEM_S
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_OGP_S;

CREATE SEQUENCE SM_OGP_S
  START WITH 1
  MAXVALUE 999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_SALE_ORDER_ITEMS_S;

CREATE SEQUENCE SM_SALE_ORDER_ITEMS_S
  START WITH 1
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_SALE_ORDERS_S;

CREATE SEQUENCE SM_SALE_ORDERS_S
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_SALES_INVOICE_ADVANCE_ID_S;

CREATE SEQUENCE SM_SALES_INVOICE_ADVANCE_ID_S
  START WITH 1
  MAXVALUE 9999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE SM_SALES_INVOICE_EXPENSE_ID_S;

CREATE SEQUENCE SM_SALES_INVOICE_EXPENSE_ID_S
  START WITH 1
  MAXVALUE 99999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE SM_SALES_INVOICE_ID_S;

CREATE SEQUENCE SM_SALES_INVOICE_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE SM_SALES_INVOICE_ITEM_ID_S;

CREATE SEQUENCE SM_SALES_INVOICE_ITEM_ID_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;

DROP SEQUENCE SM_SALES_PERSONS_S;

CREATE SEQUENCE SM_SALES_PERSONS_S
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOORDER;



 